"""Makestack MCP Server — thin translation layer over the Shell REST API.

The MCP server exposes every Shell operation as an MCP tool. It is a pure
translation layer: tool call → HTTP request to Shell REST API → return JSON.
It does NOT access UserDB directly, talk to Core directly, or contain business logic.

Every tool invocation is transparently logged to the Shell's /api/mcp-log
endpoint so the MCP Action Journal stays current without any changes to
individual tool files.

Configuration via environment variables:
    MAKESTACK_SHELL_URL    Shell base URL (default: http://localhost:3000)
    MAKESTACK_SHELL_TOKEN  Bearer token if Shell auth is enabled (default: empty)

Usage:
    # SSE transport (mounted in FastAPI at /mcp):
    from mcp_server.server import create_server
    mcp = create_server()
    app.mount("/mcp", mcp.sse_app())

    # stdio transport (for Claude Code and local AI tools):
    python -m mcp_server
"""

import json
import os
import uuid

import httpx
from mcp.server.fastmcp import FastMCP
from mcp.server.sse import TransportSecuritySettings

from .tools import binary_refs, catalogue, data, inventory, mcp_log, modules, settings, system, users, version, workshops


# ---------------------------------------------------------------------------
# Affected-path extraction
# ---------------------------------------------------------------------------


def _extract_affected_paths(
    tool_name: str, arguments: dict, result_text: str | None = None
) -> list[str]:
    """Return catalogue paths touched by this tool call.

    For update_primitive / delete_primitive: path is in the arguments.
    For create_primitive: path is auto-generated by Core — extract from result.
    All other tools default to [].
    """
    if tool_name in ("update_primitive", "delete_primitive"):
        path = arguments.get("path")
        if path:
            return [path]

    if tool_name == "create_primitive" and result_text:
        try:
            data = json.loads(result_text)
            if isinstance(data, dict):
                path = data.get("path")
                if path and isinstance(path, str):
                    return [path]
        except Exception:
            pass

    return []


# ---------------------------------------------------------------------------
# Logging FastMCP subclass
# ---------------------------------------------------------------------------


class _LoggingFastMCP(FastMCP):
    """FastMCP subclass that logs every tool invocation to /api/mcp-log.

    The log entry is written in a finally block so both successful calls and
    calls that raise an exception are captured. Logging failures are silently
    swallowed — they must never affect tool execution.
    """

    def __init__(
        self,
        *args,
        log_api: httpx.AsyncClient,
        session_id: str,
        **kwargs,
    ) -> None:
        super().__init__(*args, **kwargs)
        self._log_api = log_api
        self._session_id = session_id

    async def call_tool(self, name: str, arguments: dict | None = None):
        """Invoke the named tool and log the result to /api/mcp-log."""
        args = arguments or {}
        result_status = "success"
        result_summary: str | None = None
        result_text: str | None = None
        result = None

        try:
            result = await super().call_tool(name, arguments)

            # Extract a brief text summary from the first content block.
            if result:
                first = result[0]
                # FastMCP may return (list[ContentBlock],) or list[ContentBlock].
                if isinstance(first, list):
                    first = first[0] if first else None
                if first is not None:
                    result_text = getattr(first, "text", None)
                    result_summary = result_text[:500] if result_text else None

            return result

        except Exception as exc:
            result_status = "error"
            result_summary = str(exc)[:500]
            raise

        finally:
            affected_paths = _extract_affected_paths(name, args, result_text)
            try:
                await self._log_api.post(
                    "/api/mcp-log",
                    json={
                        "tool_name": name,
                        "tool_args": args,
                        "result_status": result_status,
                        "result_summary": result_summary,
                        "affected_paths": affected_paths,
                        "session_id": self._session_id,
                    },
                )
            except Exception:
                pass  # Logging failure must never break tool execution.


# ---------------------------------------------------------------------------
# Server factory
# ---------------------------------------------------------------------------


def create_server(api_client: httpx.AsyncClient | None = None) -> _LoggingFastMCP:
    """Create and configure the Makestack MCP server.

    Args:
        api_client: Optional pre-configured httpx client. If not provided, one is
            created from environment variables. Pass a custom client in tests to
            use an ASGI transport against the test FastAPI app.

    Returns:
        A configured _LoggingFastMCP instance with all tools registered.
    """
    if api_client is None:
        shell_url = os.getenv("MAKESTACK_SHELL_URL", "http://localhost:3000")
        shell_token = os.getenv("MAKESTACK_SHELL_TOKEN", "")
        headers: dict = {}
        if shell_token:
            headers["Authorization"] = f"Bearer {shell_token}"
        api_client = httpx.AsyncClient(
            base_url=shell_url,
            headers=headers,
            timeout=30.0,
        )

    session_id = str(uuid.uuid4())

    # Allow extra hosts via env var (comma-separated) for reverse-proxy deployments.
    # e.g. MAKESTACK_MCP_ALLOWED_HOSTS=makestack.duckdns.org
    _extra_hosts = [
        h.strip()
        for h in os.getenv("MAKESTACK_MCP_ALLOWED_HOSTS", "").split(",")
        if h.strip()
    ]
    transport_security = TransportSecuritySettings(
        enable_dns_rebinding_protection=True,
        allowed_hosts=["127.0.0.1:*", "localhost:*", "[::1]:*"] + _extra_hosts,
        allowed_origins=["http://127.0.0.1:*", "http://localhost:*", "http://[::1]:*"],
    )

    mcp = _LoggingFastMCP(
        name="makestack",
        instructions=(
            "You are connected to a Makestack Shell — a modular project management toolkit "
            "for makers (leatherworkers, cosplayers, woodworkers, 3D printers, etc.).\n\n"
            "The catalogue holds impersonal documented knowledge: techniques, materials, tools, "
            "workflows, projects, and events. Your personal inventory holds hash-pointer references "
            "to catalogue entries — what you own and when you added it.\n\n"
            "Workshops are schema-free organisational containers you can use however you like.\n\n"
            "Use get_capabilities to discover all available operations, or get_status to check "
            "system health."
        ),
        log_api=api_client,
        session_id=session_id,
        transport_security=transport_security,
    )

    # Register tool groups — order doesn't matter for MCP but keep it logical.
    catalogue.register_tools(mcp, api_client)
    binary_refs.register_tools(mcp, api_client)
    inventory.register_tools(mcp, api_client)
    workshops.register_tools(mcp, api_client)
    version.register_tools(mcp, api_client)
    settings.register_tools(mcp, api_client)
    modules.register_tools(mcp, api_client)
    data.register_tools(mcp, api_client)
    users.register_tools(mcp, api_client)
    system.register_tools(mcp, api_client)
    mcp_log.register_tools(mcp, api_client)

    return mcp
