/**
 * Module registry — auto-generated at build time.
 *
 * This file is regenerated by `scripts/generate_module_registry.py` whenever
 * a module is installed or removed. Do NOT edit by hand.
 *
 * For each installed module that has `has_frontend: true`, this file imports
 * its `registerXxxModule()` function and calls it during app init. The shell's
 * main.tsx calls `registerAllModules()` before first render.
 *
 * Each module's register function adds its panels to panel-registry and its
 * views to view-registry. Unresolved panel ids render as <UnknownPanel>;
 * unresolved view routes render as "Page not found" — neither ever throws.
 *
 * Modules that are not installed will have their import lines absent from this
 * file.
 */

// --- BEGIN GENERATED IMPORTS ---
import { registerKitchenModule } from '@kitchen-frontend'
// --- END GENERATED IMPORTS ---

export function registerAllModules(): void {
  // --- BEGIN GENERATED CALLS ---
  registerKitchenModule()
  // --- END GENERATED CALLS ---
}
