/**
 * Module panel registry — auto-generated at build time.
 *
 * This file is regenerated by `scripts/generate_module_registry.py` whenever
 * a module is installed or removed. Do NOT edit by hand.
 *
 * For each installed module that has `has_frontend: true`, this file imports
 * its `registerXxxPanels()` function and calls it during app init. The shell's
 * main.tsx calls `registerAllModulePanels()` before first render.
 *
 * Modules that are not installed will have their import lines absent from this
 * file. Unresolved panelIds render as <UnknownPanel> — they never throw.
 */

// --- BEGIN GENERATED IMPORTS ---
import { registerKitchenPanels } from '@kitchen-frontend'
// --- END GENERATED IMPORTS ---

export function registerAllModulePanels(): void {
  // --- BEGIN GENERATED CALLS ---
  registerKitchenPanels()
  // --- END GENERATED CALLS ---
}
